#!/bin/sh

cd `dirname $0`

# ---------- set up variables ---------- #

NOTIM_EODITOR_CMD=${NOTIM_EDITOR_CMD:-vim}
NOTIM_HOME=${NOTIM_HOME:-~/.notim}
NOTIM_NOTE=${NOTIM_HOME%/}/note

# ---------- main command ---------- #

NOTIM_NOTE_PATH=${NOTIM_NOTE%/}/$1
NOTIM_NOTE_DIR=`dirname $NOTIM_NOTE_PATH`

mkdir -p $NOTIM_NOTE_DIR
vim $NOTIM_NOTE_PATH

