#!/bin/sh

cd `dirname $0`

# ---------- set up variables ---------- #

NOTIM_EODITOR_CMD=${NOTIM_EDITOR_CMD:-vim}
NOTIM_HOME=${NOTIM_HOME:-~/.notim}
NOTIM_NOTE_ROOT=${NOTIM_HOME%/}/note
NOTIM_NOTE_PATH=${NOTIM_NOTE_ROOT%/}/$1

# ---------- process command line arguments ---------- #

while [ $# -gt 0 ]
do
key="$1"

case $key in
  --update)
  UPDATE_FLAG=YES
  shift
  ;;
  *)
  shift
  ;;
esac
done


# ---------- main func ---------- #

main() {
  NOTIM_NOTE_DIR=`dirname $NOTIM_NOTE_PATH`
  
  mkdir -p $NOTIM_NOTE_DIR
  vim $NOTIM_NOTE_PATH
}

# ---------- update func ---------- #

update() {
  git pull
  echo "\nRestart your shell to apply the update\n"
}

# ---------- main ---------- #

if [ "$UPDATE_FLAG" = "YES" ]; then
  update
  exit
fi

main

