#!/bin/sh

cd `dirname $0`

# ---------- set up variables ---------- #

NOTIM_EODITOR_CMD=${NOTIM_EDITOR_CMD:-vim}
NOTIM_HOME=${NOTIM_HOME:-~/.notim}
NOTIM_NOTE=${NOTIM_HOME%/}/note

# ---------- set up date directory ---------- #

mkdir -p $NOTIM_HOME/note

# ---------- main command ---------- #

vim ${NOTIM_NOTE%/}/$1

